# game options/settings
TITLE = "Flapper!"
WIDTH = 800
HEIGHT = 600
FPS = 60
FONT_NAME = 'arial'
HS_FILE = "highscore.txt"
SPRITESHEET = "flapper_sprites.png"

# Player properties
PLAYER_ACC = 0.5
PLAYER_FRICTION = -0.12
PLAYER_GRAV = 0.8
PLAYER_JUMP = 15

VERTICAL_GAP = 200
HORIZONTAL_GAP = 400
PIPE_WIDTH = 54
PIPE_HEIGHT = 322
X_SPAWN = WIDTH + HORIZONTAL_GAP - PIPE_WIDTH
GAP_BUFFER = 60

PIPE_GAPS = [200, 100, 300]

FLOOR_POS = (0, HEIGHT - 40)
FLOOR_DIMS = (WIDTH, 40)

# Starting platforms
'''PLATFORM_LIST = [(WIDTH, 0, PIPE_WIDTH, PIPE_GAPS[0]),
                 (WIDTH, PIPE_GAPS[0] + VERTICAL_GAP, PIPE_WIDTH, HEIGHT - (PIPE_GAPS[0] + VERTICAL_GAP)),

                 (WIDTH + HORIZONTAL_GAP, 0, PIPE_WIDTH, PIPE_GAPS[1]),
                 (WIDTH + HORIZONTAL_GAP, PIPE_GAPS[1] + VERTICAL_GAP, PIPE_WIDTH, HEIGHT - (PIPE_GAPS[1] + VERTICAL_GAP)),

                 (WIDTH + HORIZONTAL_GAP*2, 0, PIPE_WIDTH, PIPE_GAPS[2]),
                 (WIDTH + HORIZONTAL_GAP*2, PIPE_GAPS[2] + VERTICAL_GAP, PIPE_WIDTH, HEIGHT - (PIPE_GAPS[2] + VERTICAL_GAP))]'''

PLATFORM_LIST = [
                    (WIDTH, PIPE_GAPS[0]),
                    (WIDTH + HORIZONTAL_GAP, PIPE_GAPS[1]),
                    (WIDTH + HORIZONTAL_GAP*2, PIPE_GAPS[2])
]

# define colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)
LIGHTBLUE = (0, 155, 155)
BGCOLOR = LIGHTBLUE
